### ISSUE TITLE
output includes variants outside region

### ISSUE THREAD

**Issue by sandra-selfdecode** [rwk-unil/xSqueezeIt#2]
Hello, I discovered that variants outside my region of interest were sometimes included in my output. Is there a way to prevent this, other than filtering again with bcftools?
```
xsqueezeit -x -f chr20.xsi -r "20:614471-657881" | bcftools query -f '%ID,%POS\n'

0              20-614465-CTCTCTCTCTA-C,614465
1        20-614467-CTCTCTCTATATA-CTATA,614467
2          20-614467-CTCTCTCTATATA-CTA,614467
3            20-614467-CTCTCTCTATATA-C,614467
4      20-614469-CTCTCTATATATA-CTATATA,614469
...                                       ...
10004                    20-657856-C-T,657856
10005                    20-657864-T-G,657864
10006                    20-657871-T-C,657871
10007                    20-657879-A-G,657879
10008                    20-657881-A-G,657881

**Comment by rwk-unil** [comment]
Hello,
this is the expected behaviour for indels that overlap the edges of the region of interest.
The "-r" option was implemented the same way as for bcftools which would also report them.

https://samtools.github.io/bcftools/bcftools.html#common_options

> -r, --regions chr|chr:pos|chr:beg-end|chr:beg-[,…​]
> Comma-separated list of regions, see also -R, --regions-file. Overlapping records are matched even when the starting coordinate is outside of the region, unlike the -t/-T options where only the POS coordinate is checked. Note that -r cannot be used in combination with -R.

What you want would be the `-t/-T` option.

For the moment it is not implemented in xSqueezeIt, so you need to filter with bcftools.

I'll add the option and let you know when it is available.

Regards,
Rick

**Comment by rwk-unil** [comment]
Hello,

I have added the `-t,--targets` option.
Please recompile the latest version from the master branch and try `-t "20:614471-657881"`.
Since the option is based on HTSLIB it should give the same results at bcftools. Let me know if you have any issues.

`-t,--targets` Added with commit : 01f9056a3f5b3c4eb18377e3d42093e6329ade43
Unit test added with commit : 70ac7e78d9862fe60fb16cd0a550e09fde0807e4

Best regards,
Rick

Edit : typo

**Comment by sandra-selfdecode** [comment]
Thank you for the rapid response. I know in bcftools `-t` is slower than `-r` because it uses streaming. Is that also true in xSqueezeIt? In which case would it be faster to continue selecting with `-r` and then using `-t`?

**Comment by rwk-unil** [comment]
Hello,
You are correct `-t` is slower because it streams the whole BCF/VCF file instead of using the `.csi`/`.tbi` index.
However, because XSI splits the variant data (into a `.bcf` file) and the genotype data (into the `.xsi` file) streaming of the `.bcf` file is much faster, because there are no genotype data to decompress.

So the difference in speed between `-r` and `-t` will not be as big as with bcftools. If you have a large number of samples, the cost of `-t` for bcftools will be very big, but not with XSI (because the number of samples doesn't affect the speed of `-t` in XSI).

In some cases `-t` with xSqueezeIt will be faster than `-r` then filtering with bcftools, it depends on the size of the target region with relation to the whole file.

I would suggest to try it out with your files and queries and use what is the fastest, but in all cases `-t` will be faster with xSqueezeIt then with bcftools because xSqueezeit will only decompress and stream the variants to extract the lines matching the query (and then decompress the genotypes that are needed), whereas bcftools will need to decompress the whole file, which may take a long time (e.g., days on a full chromosome with 100-500k samples).

Edit : Reformulated a sentence for clarity.
